apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-booking-app
  template:
    metadata:
      labels:
        app: travel-booking-app
      annotations:
        ad.datadoghq.com/travel-booking-app.logs: '[{"source":"nodejs","service":"travel-booking-service"},{"source":"nodejs","service":"travel-booking-app"}]'
    spec:
      containers:
      - name: travel-booking-app
        image: your-dockerhub-username/travel-booking-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/travelEase"
        - name: PORT
          value: "3000"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"
        # Datadog APM (tracing) env variables
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "travel-booking-app"
        - name: DD_VERSION
          value: "1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: travel-booking-service
spec:
  selector:
    app: travel-booking-app
  ports:
  - port: 8070
    targetPort: 3000
  type: LoadBalancer